### ISSUE TITLE
有一个推荐的链接有问题

### ISSUE THREAD

**Issue by Aboceder** [TommyMerlin/Repository-Collection#4]
![CleanShot 2023-04-07 at 11 32 51](https://user-images.githubusercontent.com/53726224/230535755-a3e0299b-831d-4c6f-847d-3299995ed994.png)
这个，地图里面，把台湾划分到了中国以外，我刚开始还想分享来着。。。后来仔细一看。。。

**Comment by TommyMerlin** [comment]
看了一下确实有这个问题，已删除改项目，感谢指正。
